"""Generated HTML index for browsing graph artifacts."""

from __future__ import annotations

from html import escape
from pathlib import Path

from tea_kb.domain.models import KnowledgeGraph
from tea_kb.graph.timeline import major_concepts
from tea_kb.io.artifact_writer import Artifact


def site_index_artifact(graph: KnowledgeGraph) -> Artifact:
    return Artifact(Path("graph/generated/index.html"), render_site_index(graph))


def render_site_index(graph: KnowledgeGraph) -> str:
    concept_links = "\n".join(
        "<li>"
        f"<code>{escape(str(concept))}</code>: "
        f"<a href='visualizations/concept-timeline-{_concept_slug(concept)}-light.svg'>light</a> "
        f"<a href='visualizations/concept-timeline-{_concept_slug(concept)}-dark.svg'>dark</a>"
        "</li>"
        for concept, _ in major_concepts(graph)
    )
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>TEA Generated Graph</title>
  <style>
    :root {{
      color-scheme: light dark;
      --bg: #ffffff;
      --ink: #172033;
      --muted: #57606a;
      --line: #d0d7de;
      --card: #f6f8fa;
      --link: #0969da;
    }}
    @media (prefers-color-scheme: dark) {{
      :root {{
        --bg: #0b1220;
        --ink: #e5edf7;
        --muted: #9aa8bd;
        --line: #334155;
        --card: #111827;
        --link: #60a5fa;
      }}
    }}
    body {{
      background: var(--bg);
      color: var(--ink);
      font-family: ui-sans-serif, system-ui, sans-serif;
      line-height: 1.5;
      margin: 2rem auto;
      max-width: 960px;
      padding: 0 1rem;
    }}
    a {{ color: var(--link); }}
    code {{ color: var(--ink); }}
    section {{
      background: var(--card);
      border: 1px solid var(--line);
      border-radius: 8px;
      margin: 1rem 0;
      padding: 1rem;
    }}
    .muted {{ color: var(--muted); }}
  </style>
</head>
<body>
  <h1>TEA Generated Graph</h1>
  <p class="muted">Generated by <code>uv run tea-kb build</code>.</p>
  <section>
    <h2>Summary</h2>
    <ul>
      <li>Nodes: {len(graph.nodes)}</li>
      <li>Edges: {len(graph.edges)}</li>
      <li>Chunks: {len(graph.chunks)}</li>
    </ul>
  </section>
  <section>
    <h2>README Visuals</h2>
    <ul>
      <li>
        Repository system:
        <a href="visualizations/repo-system-light.svg">light</a>
        <a href="visualizations/repo-system-dark.svg">dark</a>
      </li>
      <li>
        Research support:
        <a href="visualizations/research-support-light.svg">light</a>
        <a href="visualizations/research-support-dark.svg">dark</a>
      </li>
      <li>
        Knowledge growth:
        <a href="visualizations/timeline-overview-light.svg">light</a>
        <a href="visualizations/timeline-overview-dark.svg">dark</a>
      </li>
      <li><a href="visualizations/overview.html">Interactive graph overview</a></li>
    </ul>
  </section>
  <section>
    <h2>Reports</h2>
    <ul>
      <li><a href="reports/health.md">Graph health</a></li>
      <li><a href="reports/timeline.md">Knowledge timeline</a></li>
      <li><a href="reports/duplicate-concepts.md">Duplicate concepts</a></li>
      <li><a href="reports/dense-links.md">Dense links</a></li>
      <li><a href="reports/proposed-edges.md">Proposed edges</a></li>
    </ul>
  </section>
  <section>
    <h2>Major Concept Timelines</h2>
    <ul>
      {concept_links or "<li>None</li>"}
    </ul>
  </section>
  <section>
    <h2>Machine Feeds</h2>
    <ul>
      <li><a href="nodes.jsonl">nodes.jsonl</a></li>
      <li><a href="edges.jsonl">edges.jsonl</a></li>
      <li><a href="chunks.jsonl">chunks.jsonl</a></li>
      <li><a href="concepts.jsonl">concepts.jsonl</a></li>
      <li><a href="timeline.jsonl">timeline.jsonl</a></li>
    </ul>
  </section>
</body>
</html>
"""


def _concept_slug(concept: object) -> str:
    return str(concept).removeprefix("concept:").replace(":", "-")
