"""Deterministic SVG visualizations for README and graph review."""

from __future__ import annotations

from collections import Counter, defaultdict
from collections.abc import Callable
from html import escape
from pathlib import Path

from tea_kb.domain.enums import NodeType
from tea_kb.domain.ids import ConceptId, slugify
from tea_kb.domain.models import KnowledgeGraph, KnowledgeNode
from tea_kb.graph.timeline import (
    TimelineEvent,
    events_for_concept,
    major_concepts,
    timeline_events,
)
from tea_kb.io.artifact_writer import Artifact

SVG_DIR = Path("graph/generated/visualizations")
LIGHT_PALETTE = {
    "bg": "#f8fafc",
    "card": "#ffffff",
    "ink": "#172033",
    "inverse_ink": "#ffffff",
    "muted": "#64748b",
    "line": "#cbd5e1",
    "shadow": "#0f172a",
    "blue": "#2563eb",
    "teal": "#0f766e",
    "amber": "#b45309",
    "rose": "#be123c",
    "violet": "#6d28d9",
    "green": "#15803d",
}
DARK_PALETTE = {
    "bg": "#0b1220",
    "card": "#111827",
    "ink": "#e5edf7",
    "inverse_ink": "#ffffff",
    "muted": "#9aa8bd",
    "line": "#334155",
    "shadow": "#000000",
    "blue": "#60a5fa",
    "teal": "#2dd4bf",
    "amber": "#f59e0b",
    "rose": "#fb7185",
    "violet": "#a78bfa",
    "green": "#22c55e",
}
PALETTES = {"light": LIGHT_PALETTE, "dark": DARK_PALETTE}
PALETTE = LIGHT_PALETTE


def svg_visualization_artifacts(graph: KnowledgeGraph) -> list[Artifact]:
    artifacts = [
        visualization_index_artifact(graph),
        *repo_system_svg_artifacts(graph),
        *research_support_svg_artifacts(graph),
        *timeline_overview_svg_artifacts(graph),
    ]
    artifacts.extend(
        artifact
        for concept, _ in major_concepts(graph)
        for artifact in concept_timeline_svg_artifacts(graph, concept)
    )
    return artifacts


def visualization_index_artifact(graph: KnowledgeGraph) -> Artifact:
    concept_lines = [
        (
            f"- `{concept}` - {count} node(s): "
            f"[light](concept-timeline-{_concept_slug(concept)}-light.svg), "
            f"[dark](concept-timeline-{_concept_slug(concept)}-dark.svg)"
        )
        for concept, count in major_concepts(graph)
    ]
    lines = [
        "# Generated Visualizations",
        "",
        "Generated by `uv run tea-kb build` from Markdown/frontmatter graph source.",
        "",
        "## README visuals",
        "",
        "- Repository system: [light](repo-system-light.svg), [dark](repo-system-dark.svg)",
        (
            "- Research support map: "
            "[light](research-support-light.svg), [dark](research-support-dark.svg)"
        ),
        (
            "- Knowledge base growth: "
            "[light](timeline-overview-light.svg), [dark](timeline-overview-dark.svg)"
        ),
        "",
        "## Diagnostic views",
        "",
        "- [Interactive graph overview](overview.html)",
        "",
        "## Major concept timelines",
        "",
        *(concept_lines or ["- None"]),
        "",
    ]
    return Artifact(SVG_DIR / "README.md", "\n".join(lines))


def repo_system_svg_artifacts(graph: KnowledgeGraph) -> list[Artifact]:
    return _themed_artifacts("repo-system", lambda: render_repo_system_svg(graph))


def research_support_svg_artifacts(graph: KnowledgeGraph) -> list[Artifact]:
    return _themed_artifacts("research-support", lambda: render_research_support_svg(graph))


def timeline_overview_svg_artifacts(graph: KnowledgeGraph) -> list[Artifact]:
    return _themed_artifacts("timeline-overview", lambda: render_timeline_overview_svg(graph))


def concept_timeline_svg_artifacts(graph: KnowledgeGraph, concept: ConceptId) -> list[Artifact]:
    stem = f"concept-timeline-{_concept_slug(concept)}"
    return _themed_artifacts(stem, lambda: render_concept_timeline_svg(graph, concept))


def render_repo_system_svg(graph: KnowledgeGraph) -> str:
    type_counts = Counter(node.node_type.value for node in graph.nodes.values())
    cards = [
        _card(
            52,
            148,
            230,
            210,
            "Markdown Source",
            [
                f"{len(graph.nodes)} graph nodes",
                f"{type_counts.get(NodeType.NOTE.value, 0)} notes",
                f"{type_counts.get(NodeType.CONCEPT.value, 0)} concepts",
                "frontmatter is canonical",
            ],
            PALETTE["teal"],
        ),
        _card(
            338,
            120,
            240,
            266,
            "tea-kb Lifecycle",
            [
                "parse frontmatter",
                "validate contracts",
                "build graph",
                "report health",
                "render visualizations",
            ],
            PALETTE["blue"],
        ),
        _card(
            634,
            148,
            230,
            210,
            "Generated Brew",
            [
                "nodes / edges / chunks",
                "timeline events",
                "Markdown reports",
                "SVG + HTML views",
            ],
            PALETTE["amber"],
        ),
        _card(
            920,
            120,
            230,
            266,
            "Consumers",
            [
                "README visuals",
                "GitHub Actions",
                "human review",
                "future search/RAG",
                "agent context",
            ],
            PALETTE["rose"],
        ),
    ]
    lines = [
        _svg_open(1200, 520, "How tea-style works"),
        _title("How tea-style Works", "Markdown stays canonical. Tooling regenerates evidence."),
        *cards,
        _arrow(282, 252, 338, 252),
        _arrow(578, 252, 634, 252),
        _arrow(864, 252, 920, 252),
        _loop_arrow(),
        _text(600, 456, "CI enforces: validate -> tests -> build --check", 18, "600", "middle"),
        "</svg>",
    ]
    return "\n".join(lines)


def render_research_support_svg(graph: KnowledgeGraph) -> str:
    type_counts = Counter(node.node_type.value for node in graph.nodes.values())
    top_nodes = sorted(
        graph.nodes.values(),
        key=lambda node: (
            len(graph.inbound_edges(node.id)) + len(graph.outbound_edges(node.id)),
            str(node.id),
        ),
        reverse=True,
    )[:5]
    top_concepts = major_concepts(graph, limit=5)
    lines = [
        _svg_open(1200, 620, "Research and doctrine support map"),
        _title(
            "Research Support Map",
            "Doctrine, standards, decisions, notes, and examples support each other as a graph.",
        ),
        _metric_card(
            58, 136, "Doctrines", type_counts.get(NodeType.DOCTRINE.value, 0), PALETTE["violet"]
        ),
        _metric_card(
            292, 136, "Standards", type_counts.get(NodeType.STANDARD.value, 0), PALETTE["blue"]
        ),
        _metric_card(
            526, 136, "Decisions", type_counts.get(NodeType.DECISION.value, 0), PALETTE["teal"]
        ),
        _metric_card(760, 136, "Notes", type_counts.get(NodeType.NOTE.value, 0), PALETTE["green"]),
        _metric_card(
            994, 136, "Examples", type_counts.get(NodeType.EXAMPLE.value, 0), PALETTE["amber"]
        ),
        _text(58, 292, "Highest-degree doctrine nodes", 20, "700", "start"),
        _text(658, 292, "Major concepts in use", 20, "700", "start"),
        *_ranked_rows(58, 318, top_nodes),
        *_concept_rows(658, 318, top_concepts),
        _text(
            600,
            570,
            f"{len(graph.edges)} semantic edges connect research into reviewable paths.",
            18,
            "600",
            "middle",
        ),
        "</svg>",
    ]
    return "\n".join(lines)


def render_timeline_overview_svg(graph: KnowledgeGraph) -> str:
    events = timeline_events(graph)
    by_date: defaultdict[str, list[str]] = defaultdict(list)
    by_type = Counter(event.node_type.value for event in events)
    for event in events:
        by_date[event.date.isoformat()].append(event.event_type)

    dates = sorted(by_date)
    points = _timeline_points(dates, 120, 1080)
    lines = [
        _svg_open(1200, 520, "Knowledge base growth timeline"),
        _title(
            "Knowledge Base Growth",
            "Generated from `created` and `updated` frontmatter dates.",
        ),
        f"<line x1='120' y1='248' x2='1080' y2='248' stroke='{PALETTE['line']}' stroke-width='4'/>",
    ]
    if not events:
        lines.append(_text(600, 260, "No dated graph nodes yet.", 22, "700", "middle"))
    for date_value in dates:
        x = points[date_value]
        events_for_date = by_date[date_value]
        created = events_for_date.count("created")
        updated = events_for_date.count("updated")
        total = len(events_for_date)
        radius = min(42, 14 + total * 2)
        lines.extend(
            [
                f"<circle cx='{x}' cy='248' r='{radius}' fill='{PALETTE['blue']}' opacity='0.92'/>",
                _text(x, 252, str(total), 18, "800", "middle", PALETTE["inverse_ink"]),
                _text(x, 188, date_value, 16, "700", "middle"),
                _text(x, 310, f"{created} created / {updated} updated", 14, "600", "middle"),
            ]
        )
    lines.extend(
        [
            _text(84, 396, "Event mix", 18, "700", "start"),
            *_type_badges(84, 418, by_type),
            _text(
                600,
                476,
                f"{len(events)} timeline event(s) across {len(dates)} date(s).",
                18,
                "600",
                "middle",
            ),
            "</svg>",
        ]
    )
    return "\n".join(lines)


def render_concept_timeline_svg(graph: KnowledgeGraph, concept: ConceptId) -> str:
    events = events_for_concept(timeline_events(graph), concept)
    shown = events[:18]
    height = max(320, 164 + len(shown) * 74)
    lines = [
        _svg_open(1200, height, f"Timeline for {concept}"),
        _title(
            f"Concept Timeline: {concept}",
            f"{len(events)} dated event(s) associated with this concept.",
        ),
        (
            f"<line x1='168' y1='128' x2='168' y2='{height - 64}' "
            f"stroke='{PALETTE['line']}' stroke-width='4'/>"
        ),
    ]
    if not shown:
        lines.append(_text(600, 220, "No dated events for this concept.", 20, "700", "middle"))
    for index, event in enumerate(shown):
        y = 142 + index * 74
        color = PALETTE["green"] if event.event_type == "created" else PALETTE["amber"]
        lines.extend(
            [
                f"<circle cx='168' cy='{y}' r='10' fill='{color}'/>",
                _text(126, y + 5, event.date.isoformat(), 14, "700", "end"),
                _event_card(204, y - 28, event, color),
            ]
        )
    if len(events) > len(shown):
        lines.append(
            _text(
                600,
                height - 34,
                f"Showing {len(shown)} of {len(events)} events. See timeline.jsonl.",
                15,
                "600",
                "middle",
            )
        )
    lines.append("</svg>")
    return "\n".join(lines)


def _themed_artifacts(stem: str, renderer: Callable[[], str]) -> list[Artifact]:
    return [
        Artifact(SVG_DIR / f"{stem}-{theme}.svg", _render_with_palette(palette, renderer))
        for theme, palette in PALETTES.items()
    ]


def _render_with_palette(palette: dict[str, str], renderer: Callable[[], str]) -> str:
    global PALETTE

    previous = PALETTE
    try:
        PALETTE = palette
        return renderer()
    finally:
        PALETTE = previous


def _svg_open(width: int, height: int, label: str) -> str:
    return "\n".join(
        [
            (
                '<svg xmlns="http://www.w3.org/2000/svg" role="img" '
                f'aria-label="{escape(label)}" viewBox="0 0 {width} {height}">'
            ),
            "<defs>",
            (
                '  <marker id="arrow" markerWidth="10" markerHeight="10" '
                'refX="8" refY="3" orient="auto" markerUnits="strokeWidth">'
            ),
            f'    <path d="M0,0 L0,6 L9,3 z" fill="{PALETTE["muted"]}"/>',
            "  </marker>",
            '  <filter id="shadow" x="-10%" y="-10%" width="120%" height="130%">',
            (
                '    <feDropShadow dx="0" dy="4" stdDeviation="5" '
                f'flood-color="{PALETTE["shadow"]}" flood-opacity="0.12"/>'
            ),
            "  </filter>",
            "</defs>",
            f'<rect width="100%" height="100%" rx="0" fill="{PALETTE["bg"]}"/>',
        ]
    )


def _title(title: str, subtitle: str) -> str:
    return "\n".join(
        [
            _text(52, 62, title, 30, "800", "start"),
            _text(52, 96, subtitle, 16, "500", "start", PALETTE["muted"]),
        ]
    )


def _card(x: int, y: int, width: int, height: int, title: str, lines: list[str], color: str) -> str:
    body = [
        (
            f"<rect x='{x}' y='{y}' width='{width}' height='{height}' rx='10' "
            f"fill='{PALETTE['card']}' stroke='{color}' "
            "stroke-width='2' filter='url(#shadow)'/>"
        ),
        f"<rect x='{x}' y='{y}' width='{width}' height='12' rx='6' fill='{color}'/>",
        _text(x + 20, y + 46, title, 19, "800", "start"),
    ]
    body.extend(
        _text(x + 20, y + 80 + index * 28, line, 15, "600", "start", PALETTE["muted"])
        for index, line in enumerate(lines)
    )
    return "\n".join(body)


def _metric_card(x: int, y: int, label: str, value: int, color: str) -> str:
    return "\n".join(
        [
            (
                f"<rect x='{x}' y='{y}' width='148' height='104' rx='10' "
                f"fill='{PALETTE['card']}' stroke='{color}' "
                "stroke-width='2' filter='url(#shadow)'/>"
            ),
            _text(x + 24, y + 38, label, 16, "700", "start", PALETTE["muted"]),
            _text(x + 24, y + 76, str(value), 34, "800", "start", color),
        ]
    )


def _ranked_rows(x: int, y: int, nodes: list[KnowledgeNode]) -> list[str]:
    rows: list[str] = []
    for index, node in enumerate(nodes):
        node_id = str(node.id)
        title = str(node.title)
        path = node.path
        row_y = y + index * 44
        rows.extend(
            [
                f"<a href='../../../{escape(path.as_posix())}'>",
                (
                    f"<rect x='{x}' y='{row_y}' width='520' height='34' rx='7' "
                    f"fill='{PALETTE['card']}' stroke='{PALETTE['line']}'/>"
                ),
                _text(x + 14, row_y + 22, _truncate(title, 46), 14, "700", "start"),
                _text(
                    x + 376,
                    row_y + 22,
                    _truncate(node_id, 34),
                    12,
                    "600",
                    "start",
                    PALETTE["muted"],
                ),
                "</a>",
            ]
        )
    return rows


def _concept_rows(x: int, y: int, concepts: tuple[tuple[ConceptId, int], ...]) -> list[str]:
    rows: list[str] = []
    for index, (concept, count) in enumerate(concepts):
        row_y = y + index * 44
        width = min(420, 110 + count * 18)
        fill_width = min(width, 64 + count * 14)
        rows.extend(
            [
                (
                    f"<rect x='{x}' y='{row_y}' width='{width}' height='34' rx='7' "
                    f"fill='{PALETTE['card']}' stroke='{PALETTE['line']}'/>"
                ),
                (
                    f"<rect x='{x}' y='{row_y}' width='{fill_width}' height='34' "
                    f"rx='7' fill='{PALETTE['blue']}' opacity='0.12'/>"
                ),
                _text(x + 14, row_y + 22, str(concept), 14, "700", "start"),
                _text(
                    x + width - 16,
                    row_y + 22,
                    str(count),
                    14,
                    "800",
                    "end",
                    PALETTE["blue"],
                ),
            ]
        )
    return rows


def _event_card(x: int, y: int, event: TimelineEvent, color: str) -> str:
    title = _truncate(str(event.title), 72)
    node_id = _truncate(str(event.node_id), 62)
    node_type = event.node_type.value
    path = event.path
    event_type = str(event.event_type)
    return "\n".join(
        [
            f"<a href='../../../{escape(path.as_posix())}'>",
            (
                f"<rect x='{x}' y='{y}' width='880' height='56' rx='9' "
                f"fill='{PALETTE['card']}' stroke='{PALETTE['line']}' "
                "filter='url(#shadow)'/>"
            ),
            (
                f"<rect x='{x + 18}' y='{y + 16}' width='82' height='24' "
                f"rx='12' fill='{color}' opacity='0.12'/>"
            ),
            _text(x + 59, y + 33, event_type, 12, "800", "middle", color),
            _text(x + 118, y + 23, title, 15, "800", "start"),
            _text(
                x + 118,
                y + 43,
                f"{node_type} - {node_id}",
                12,
                "600",
                "start",
                PALETTE["muted"],
            ),
            "</a>",
        ]
    )


def _type_badges(x: int, y: int, counts: Counter[str]) -> list[str]:
    colors = [
        PALETTE["blue"],
        PALETTE["teal"],
        PALETTE["amber"],
        PALETTE["rose"],
        PALETTE["violet"],
    ]
    rows: list[str] = []
    cursor = x
    for index, (label, count) in enumerate(sorted(counts.items())):
        color = colors[index % len(colors)]
        width = 128 + len(label) * 7
        rows.extend(
            [
                (
                    f"<rect x='{cursor}' y='{y}' width='{width}' height='38' "
                    f"rx='19' fill='{PALETTE['card']}' stroke='{color}'/>"
                ),
                _text(cursor + 18, y + 24, f"{label}: {count}", 14, "800", "start", color),
            ]
        )
        cursor += width + 14
    return rows


def _timeline_points(dates: list[str], start: int, end: int) -> dict[str, int]:
    if not dates:
        return {}
    if len(dates) == 1:
        return {dates[0]: (start + end) // 2}
    step = (end - start) / (len(dates) - 1)
    return {date_value: round(start + index * step) for index, date_value in enumerate(dates)}


def _arrow(x1: int, y1: int, x2: int, y2: int) -> str:
    return (
        f"<line x1='{x1}' y1='{y1}' x2='{x2}' y2='{y2}' "
        f"stroke='{PALETTE['muted']}' stroke-width='3' marker-end='url(#arrow)'/>"
    )


def _loop_arrow() -> str:
    return (
        "<path d='M1040 398 C850 482, 338 482, 160 374' fill='none' "
        f"stroke='{PALETTE['muted']}' stroke-width='3' stroke-dasharray='8 8' "
        "marker-end='url(#arrow)'/>"
    )


def _text(
    x: int,
    y: int,
    value: str,
    size: int,
    weight: str,
    anchor: str,
    fill: str | None = None,
) -> str:
    color = fill or PALETTE["ink"]
    return (
        f"<text x='{x}' y='{y}' "
        "font-family='Inter, ui-sans-serif, system-ui, sans-serif' "
        f"font-size='{size}' font-weight='{weight}' text-anchor='{anchor}' "
        f"fill='{color}'>{escape(value)}</text>"
    )


def _truncate(value: str, limit: int) -> str:
    if len(value) <= limit:
        return value
    return value[: limit - 3] + "..."


def _concept_slug(concept: ConceptId) -> str:
    return slugify(str(concept).removeprefix("concept:"))
